### ISSUE TITLE
How are the image features extracted with detectron2?

### ISSUE THREAD

**Issue by fomalhautb** [jamespark3922/visual-comet#1]
In the README file, it says "The features are extracted using the model mask_rcnn_R_101_C4_3x.yaml in detectron2 repo." but I can't find the code for it. Is there any extra code for feature extraction?

**Comment by jamespark3922** [comment]
I referenced someone's code from here https://github.com/airsplay/py-bottom-up-attention/blob/master/demo/demo_feature_extraction_attr.ipynb. but I just added notebook for feature extraction that I used for vcr images and bounding boxes: `demo/get_bbox_features_vcr.ipynb`

**Comment by fomalhautb** [comment]
> I referenced someone's code from here https://github.com/airsplay/py-bottom-up-attention/blob/master/demo/demo_feature_extraction_attr.ipynb. but I just added notebook for feature extraction that I used for vcr images and bounding boxes: `demo/get_bbox_features_vcr.ipynb`

Thank you very much!

**Comment by fomalhautb** [comment]
> I referenced someone's code from here https://github.com/airsplay/py-bottom-up-attention/blob/master/demo/demo_feature_extraction_attr.ipynb. but I just added notebook for feature extraction that I used for vcr images and bounding boxes: `demo/get_bbox_features_vcr.ipynb`

As I understand the `demo/get_bbox_features_vcr.ipynb` script, it loads the bounding box from the metadata of VCR and computes the ROI pooled features based on the bounded region. But is that maybe a small data leak? Since VisualComet has no bounding box input data. Or are we allowed to use all the data from VCR?

**Comment by jamespark3922** [comment]
That is correct. As mentioned in README, the annotations in VisualComet use the same number tags referencing detected objects in VCR images, so you will need the bounding boxes from VCR, which I think is fine. Note that we don't cover all the images in VCR though.
