### ISSUE TITLE
Line 73 of dataloaders/vcg_generation.py should end the truncation with a begin_inference token, not end_inference

### ISSUE THREAD

**Issue by BrandonLiang** [jamespark3922/visual-comet#2]
As titled.
Because, for generation's purpose, the last token of the input should be one of the three tokenizer.begin_inferences, not end_inference (which is suitable for training/fine-tuning).

https://github.com/jamespark3922/visual-comet/blob/master/dataloaders/vcg_generation.py#L73

Suggested fix:
```

if len(new_tokens) > max_seq_len:
    begin_inference = tokens[-1][0]
    assert begin_inference in tokenizer.begin_inferences.values()
    new_tokens = new_tokens[:max_seq_len - 1] + [begin_inference]
else:
    ......

```

**Comment by jamespark3922** [comment]
Hi Brandon, the code does attach the end_inference token at the end following the fine-tuning format.
But notice that in [https://github.com/jamespark3922/visual-comet/blob/df8b8f8ac27f41c6340985b09967b61173f3a847/scripts/run_generation.py#L401-L407](https://github.com/jamespark3922/visual-comet/blob/df8b8f8ac27f41c6340985b09967b61173f3a847/scripts/run_generation.py#L401-L407]):

```
prompt_token_idx = begin_inference[0]
end_token = tokenizer.convert_tokens_to_ids([tokenizer.end_inference])[0]

# cut off
idx_of_prompt_token = (context_orig == prompt_token_idx).nonzero()[0][1].item()
context[:,idx_of_prompt_token] = prompt_token_idx
context_input = context[:, :idx_of_prompt_token + 1]
```

We cut off the context_input up to begin_inference token, so the code you linked doesn't really take effect, and the generation starts with the correct token. Regardless, I will modify the code to avoid this confusion.
