### ISSUE TITLE
event+place evaluation

### ISSUE THREAD

**Issue by jayleicn** [jamespark3922/visual-comet#6]
Hi James,

Could you elaborate on how you evaluate event+place generation? Did you aggregate event and place text correspond to the same image together as ground-truth for evaluation? It would be great if you can share the evaluation code for it. Thanks!

Best,
Jie

**Comment by jamespark3922** [comment]
Hi Jie,

For evaluating event + place generation in appendix, I just aggregated the two together as one sentence and ran the language metrics used for captioning.

**Comment by jayleicn** [comment]
Thanks James for the details, closing this.
